// AUTO-GENERATED by scripts/gen-schema.mjs — DO NOT EDIT.
// Source of truth: scripts/db-spec.mjs. Regenerate: npm run db:gen
import { pgTable, text, bigint, integer, jsonb, boolean, doublePrecision, uniqueIndex, index } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createId } from "../lib/utils";

export const organizations = pgTable("organizations", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  planId: text("plan_id"),
  signingKeyId: text("signing_key_id"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  archivedAt: bigint("archived_at", { mode: "number" }),
}, (t) => ({
    organizationsSlugUniq: uniqueIndex("organizations_slug_uniq").on(t.slug),
}));

export const users = pgTable("users", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  name: text("name").notNull(),
  email: text("email").notNull(),
  passwordHash: text("password_hash"),
  emailVerified: bigint("email_verified", { mode: "number" }),
  image: text("image"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    usersEmailUniq: uniqueIndex("users_email_uniq").on(t.email),
}));

export const memberships = pgTable("memberships", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
  role: text("role").notNull().default("viewer"),
  invitedBy: text("invited_by"),
  invitedAt: bigint("invited_at", { mode: "number" }),
  acceptedAt: bigint("accepted_at", { mode: "number" }),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    membershipsOrgIdUserIdUniq: uniqueIndex("memberships_org_id_user_id_uniq").on(t.orgId, t.userId),
    membershipsUserIdIdx: index("memberships_user_id_idx").on(t.userId),
}));

export const sessions = pgTable("sessions", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
  orgId: text("org_id"),
  tokenHash: text("token_hash").notNull(),
  ip: text("ip"),
  userAgent: text("user_agent"),
  lastSeenAt: bigint("last_seen_at", { mode: "number" }),
  revokedAt: bigint("revoked_at", { mode: "number" }),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    sessionsTokenHashUniq: uniqueIndex("sessions_token_hash_uniq").on(t.tokenHash),
    sessionsUserIdIdx: index("sessions_user_id_idx").on(t.userId),
}));

export const projects = pgTable("projects", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  name: text("name").notNull(),
  description: text("description"),
  agentEndpoint: text("agent_endpoint"),
  agentMethod: text("agent_method").notNull().default("POST"),
  agentType: text("agent_type"),
  agentHeaders: jsonb("agent_headers"),
  defaultModel: text("default_model").notNull().default("gpt-4o-mini"),
  judgeBaseUrl: text("judge_base_url"),
  judgeModel: text("judge_model"),
  createdBy: text("created_by"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
}, (t) => ({
    projectsOrgIdIdx: index("projects_org_id_idx").on(t.orgId),
}));

export const secrets = pgTable("secrets", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  refType: text("ref_type").notNull(),
  refId: text("ref_id").notNull(),
  name: text("name").notNull(),
  ciphertext: text("ciphertext").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
}, (t) => ({
    secretsOrgIdRefTypeRefIdNameUniq: uniqueIndex("secrets_org_id_ref_type_ref_id_name_uniq").on(t.orgId, t.refType, t.refId, t.name),
}));

export const testCases = pgTable("test_cases", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  title: text("title").notNull(),
  input: text("input").notNull(),
  expectedOutput: text("expected_output"),
  category: text("category"),
  order: integer("order").notNull().default(0),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
}, (t) => ({
    testCasesOrgIdIdx: index("test_cases_org_id_idx").on(t.orgId),
    testCasesProjectIdIdx: index("test_cases_project_id_idx").on(t.projectId),
}));

export const runs = pgTable("runs", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  name: text("name"),
  status: text("status").notNull().default("queued"),
  totalCases: integer("total_cases").notNull().default(0),
  passCount: integer("pass_count").notNull().default(0),
  failCount: integer("fail_count").notNull().default(0),
  partialCount: integer("partial_count").notNull().default(0),
  unratedCount: integer("unrated_count").notNull().default(0),
  passRate: integer("pass_rate"),
  triggerType: text("trigger_type").notNull().default("manual"),
  triggeredBy: text("triggered_by"),
  modelUsed: text("model_used"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  completedAt: bigint("completed_at", { mode: "number" }),
}, (t) => ({
    runsOrgIdIdx: index("runs_org_id_idx").on(t.orgId),
    runsProjectIdIdx: index("runs_project_id_idx").on(t.projectId),
}));

export const runResults = pgTable("run_results", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runId: text("run_id").references(() => runs.id, { onDelete: "cascade" }).notNull(),
  testCaseId: text("test_case_id").references(() => testCases.id, { onDelete: "cascade" }).notNull(),
  agentResponse: text("agent_response"),
  responseTimeMs: integer("response_time_ms"),
  status: text("status").notNull().default("pending"),
  errorMessage: text("error_message"),
  needsHuman: boolean("needs_human").notNull().default(false),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    runResultsOrgIdIdx: index("run_results_org_id_idx").on(t.orgId),
    runResultsRunIdIdx: index("run_results_run_id_idx").on(t.runId),
}));

export const jobs = pgTable("jobs", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  type: text("type").notNull(),
  payload: jsonb("payload"),
  status: text("status").notNull().default("queued"),
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  runAfter: bigint("run_after", { mode: "number" }).notNull(),
  lockedAt: bigint("locked_at", { mode: "number" }),
  lockedBy: text("locked_by"),
  lastError: text("last_error"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
}, (t) => ({
    jobsStatusIdx: index("jobs_status_idx").on(t.status),
    jobsOrgIdIdx: index("jobs_org_id_idx").on(t.orgId),
}));

export const apiKeys = pgTable("api_keys", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id"),
  name: text("name").notNull(),
  keyHash: text("key_hash").notNull(),
  keyPrefix: text("key_prefix").notNull(),
  scopes: jsonb("scopes"),
  createdBy: text("created_by"),
  lastUsedAt: bigint("last_used_at", { mode: "number" }),
  expiresAt: bigint("expires_at", { mode: "number" }),
  revokedAt: bigint("revoked_at", { mode: "number" }),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    apiKeysKeyHashUniq: uniqueIndex("api_keys_key_hash_uniq").on(t.keyHash),
    apiKeysOrgIdIdx: index("api_keys_org_id_idx").on(t.orgId),
}));

export const rubrics = pgTable("rubrics", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  name: text("name").notNull(),
  version: integer("version").notNull().default(1),
  kind: text("kind").notNull().default("ordinal"),
  labels: jsonb("labels").notNull(),
  scaleMin: integer("scale_min"),
  scaleMax: integer("scale_max"),
  alwaysHuman: boolean("always_human").notNull().default(false),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    rubricsProjectIdNameVersionUniq: uniqueIndex("rubrics_project_id_name_version_uniq").on(t.projectId, t.name, t.version),
    rubricsOrgIdIdx: index("rubrics_org_id_idx").on(t.orgId),
    rubricsProjectIdIdx: index("rubrics_project_id_idx").on(t.projectId),
}));

export const aiScores = pgTable("ai_scores", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runResultId: text("run_result_id").references(() => runResults.id, { onDelete: "cascade" }).notNull(),
  rubricVersionId: text("rubric_version_id"),
  judgeConfigVersionId: text("judge_config_version_id"),
  provider: text("provider"),
  model: text("model").notNull(),
  modelResolved: text("model_resolved"),
  promptHash: text("prompt_hash"),
  label: text("label").notNull(),
  scoreNum: doublePrecision("score_num"),
  confidence: doublePrecision("confidence"),
  selfConsistency: doublePrecision("self_consistency"),
  disagreement: doublePrecision("disagreement"),
  rationale: text("rationale"),
  raw: jsonb("raw"),
  idempotencyKey: text("idempotency_key").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    aiScoresIdempotencyKeyUniq: uniqueIndex("ai_scores_idempotency_key_uniq").on(t.idempotencyKey),
    aiScoresOrgIdIdx: index("ai_scores_org_id_idx").on(t.orgId),
    aiScoresRunResultIdIdx: index("ai_scores_run_result_id_idx").on(t.runResultId),
}));

export const humanRatings = pgTable("human_ratings", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runResultId: text("run_result_id").references(() => runResults.id, { onDelete: "cascade" }).notNull(),
  rubricVersionId: text("rubric_version_id"),
  reviewerId: text("reviewer_id"),
  label: text("label").notNull(),
  scoreNum: doublePrecision("score_num"),
  rationale: text("rationale"),
  confidence: doublePrecision("confidence"),
  supersedesId: text("supersedes_id"),
  credentialSnapshot: jsonb("credential_snapshot"),
  signature: text("signature"),
  signingKeyId: text("signing_key_id"),
  attemptId: text("attempt_id").notNull(),
  signedAt: bigint("signed_at", { mode: "number" }),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    humanRatingsRunResultIdReviewerIdAttemptIdUniq: uniqueIndex("human_ratings_run_result_id_reviewer_id_attempt_id_uniq").on(t.runResultId, t.reviewerId, t.attemptId),
    humanRatingsOrgIdIdx: index("human_ratings_org_id_idx").on(t.orgId),
    humanRatingsRunResultIdIdx: index("human_ratings_run_result_id_idx").on(t.runResultId),
    humanRatingsRunResultIdReviewerIdCurrentUniq: uniqueIndex("human_ratings_run_result_id_reviewer_id_current_uniq").on(t.runResultId, t.reviewerId).where(sql`${t.supersedesId} is null`),
}));

export const adjudications = pgTable("adjudications", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runResultId: text("run_result_id").references(() => runResults.id, { onDelete: "cascade" }).notNull(),
  rubricVersionId: text("rubric_version_id"),
  finalLabel: text("final_label").notNull(),
  method: text("method").notNull(),
  weightingScheme: text("weighting_scheme"),
  agreementSummary: jsonb("agreement_summary"),
  decidedBy: text("decided_by"),
  decidedAt: bigint("decided_at", { mode: "number" }).notNull(),
  locked: boolean("locked").notNull().default(false),
}, (t) => ({
    adjudicationsRunResultIdUniq: uniqueIndex("adjudications_run_result_id_uniq").on(t.runResultId),
    adjudicationsOrgIdIdx: index("adjudications_org_id_idx").on(t.orgId),
}));

export const agreementMetrics = pgTable("agreement_metrics", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  scopeType: text("scope_type").notNull(),
  scopeId: text("scope_id").notNull(),
  rubricVersionId: text("rubric_version_id"),
  aiHumanAgreementPct: doublePrecision("ai_human_agreement_pct"),
  aiHumanConfusion: jsonb("ai_human_confusion"),
  kappa: doublePrecision("kappa"),
  kappaMethod: text("kappa_method"),
  weightingScheme: text("weighting_scheme"),
  nItems: integer("n_items"),
  nRaters: integer("n_raters"),
  ciLo: doublePrecision("ci_lo"),
  ciHi: doublePrecision("ci_hi"),
  windowStart: bigint("window_start", { mode: "number" }),
  windowEnd: bigint("window_end", { mode: "number" }),
  computedAt: bigint("computed_at", { mode: "number" }).notNull(),
}, (t) => ({
    agreementMetricsOrgIdIdx: index("agreement_metrics_org_id_idx").on(t.orgId),
    agreementMetricsScopeTypeScopeIdIdx: index("agreement_metrics_scope_type_scope_id_idx").on(t.scopeType, t.scopeId),
}));

export const judgeCalibration = pgTable("judge_calibration", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  judgeModel: text("judge_model").notNull(),
  judgePromptHash: text("judge_prompt_hash"),
  weightingScheme: text("weighting_scheme"),
  windowStart: bigint("window_start", { mode: "number" }),
  windowEnd: bigint("window_end", { mode: "number" }),
  sampleN: integer("sample_n"),
  auditSampleN: integer("audit_sample_n"),
  agreementPct: doublePrecision("agreement_pct"),
  weightedKappa: doublePrecision("weighted_kappa"),
  confusion: jsonb("confusion"),
  bias: jsonb("bias"),
  meanAbsScoreError: doublePrecision("mean_abs_score_error"),
  tau: doublePrecision("tau"),
  published: boolean("published").notNull().default(false),
  computedAt: bigint("computed_at", { mode: "number" }).notNull(),
}, (t) => ({
    judgeCalibrationOrgIdIdx: index("judge_calibration_org_id_idx").on(t.orgId),
    judgeCalibrationProjectIdIdx: index("judge_calibration_project_id_idx").on(t.projectId),
}));

export const signoffPolicies = pgTable("signoff_policies", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  minReviewers: integer("min_reviewers").notNull().default(1),
  requiredRole: text("required_role"),
  requireVerifiedCredential: boolean("require_verified_credential").notNull().default(false),
  minKappa: doublePrecision("min_kappa"),
  isActive: boolean("is_active").notNull().default(true),
  createdBy: text("created_by"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    signoffPoliciesOrgIdIdx: index("signoff_policies_org_id_idx").on(t.orgId),
    signoffPoliciesProjectIdIdx: index("signoff_policies_project_id_idx").on(t.projectId),
}));

export const runSignoffs = pgTable("run_signoffs", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runId: text("run_id").references(() => runs.id, { onDelete: "cascade" }).notNull(),
  reviewerId: text("reviewer_id").notNull(),
  decision: text("decision").notNull(),
  note: text("note"),
  credentialSnapshot: jsonb("credential_snapshot"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    runSignoffsRunIdReviewerIdUniq: uniqueIndex("run_signoffs_run_id_reviewer_id_uniq").on(t.runId, t.reviewerId),
    runSignoffsOrgIdIdx: index("run_signoffs_org_id_idx").on(t.orgId),
    runSignoffsRunIdIdx: index("run_signoffs_run_id_idx").on(t.runId),
}));

export const signingKeys = pgTable("signing_keys", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id"),
  publicKeyPem: text("public_key_pem").notNull(),
  privateKeySecretId: text("private_key_secret_id"),
  algo: text("algo").notNull().default("ed25519"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  retiredAt: bigint("retired_at", { mode: "number" }),
}, (t) => ({
    signingKeysOrgIdIdx: index("signing_keys_org_id_idx").on(t.orgId),
}));

export const evalCertificates = pgTable("eval_certificates", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runId: text("run_id").references(() => runs.id, { onDelete: "cascade" }).notNull(),
  contentHash: text("content_hash").notNull(),
  signature: text("signature").notNull(),
  signingKeyId: text("signing_key_id").notNull(),
  algo: text("algo").notNull().default("ed25519"),
  publicKeyPem: text("public_key_pem").notNull(),
  canonicalJson: text("canonical_json"),
  payload: jsonb("payload"),
  weightingScheme: text("weighting_scheme"),
  isPublic: boolean("is_public").notNull().default(false),
  signedAt: bigint("signed_at", { mode: "number" }).notNull(),
  expiresAt: bigint("expires_at", { mode: "number" }),
}, (t) => ({
    evalCertificatesRunIdUniq: uniqueIndex("eval_certificates_run_id_uniq").on(t.runId),
    evalCertificatesOrgIdIdx: index("eval_certificates_org_id_idx").on(t.orgId),
}));

export const webhooks = pgTable("webhooks", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id"),
  url: text("url").notNull(),
  secretCiphertext: text("secret_ciphertext").notNull(),
  events: jsonb("events").notNull(),
  isActive: boolean("is_active").notNull().default(true),
  createdBy: text("created_by"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    webhooksOrgIdIdx: index("webhooks_org_id_idx").on(t.orgId),
    webhooksProjectIdIdx: index("webhooks_project_id_idx").on(t.projectId),
}));

export const webhookDeliveries = pgTable("webhook_deliveries", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  webhookId: text("webhook_id").references(() => webhooks.id, { onDelete: "cascade" }).notNull(),
  event: text("event").notNull(),
  payload: jsonb("payload"),
  status: text("status").notNull().default("pending"),
  attempts: integer("attempts").notNull().default(0),
  responseStatus: integer("response_status"),
  lastError: text("last_error"),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
  updatedAt: bigint("updated_at", { mode: "number" }).notNull(),
}, (t) => ({
    webhookDeliveriesOrgIdIdx: index("webhook_deliveries_org_id_idx").on(t.orgId),
    webhookDeliveriesWebhookIdIdx: index("webhook_deliveries_webhook_id_idx").on(t.webhookId),
}));

export const rateLimits = pgTable("rate_limits", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  bucket: text("bucket").notNull(),
  windowStart: bigint("window_start", { mode: "number" }).notNull(),
  count: integer("count").notNull().default(0),
}, (t) => ({
    rateLimitsBucketWindowStartUniq: uniqueIndex("rate_limits_bucket_window_start_uniq").on(t.bucket, t.windowStart),
    rateLimitsWindowStartIdx: index("rate_limits_window_start_idx").on(t.windowStart),
}));

export const passwordResetTokens = pgTable("password_reset_tokens", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
  tokenHash: text("token_hash").notNull(),
  expiresAt: bigint("expires_at", { mode: "number" }).notNull(),
  usedAt: bigint("used_at", { mode: "number" }),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    passwordResetTokensTokenHashUniq: uniqueIndex("password_reset_tokens_token_hash_uniq").on(t.tokenHash),
    passwordResetTokensUserIdIdx: index("password_reset_tokens_user_id_idx").on(t.userId),
}));

export const auditEvents = pgTable("audit_events", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  seq: integer("seq").notNull(),
  actorId: text("actor_id"),
  action: text("action").notNull(),
  resourceType: text("resource_type"),
  resourceId: text("resource_id"),
  details: jsonb("details"),
  prevHash: text("prev_hash").notNull(),
  hash: text("hash").notNull(),
  createdAt: bigint("created_at", { mode: "number" }).notNull(),
}, (t) => ({
    auditEventsOrgIdSeqUniq: uniqueIndex("audit_events_org_id_seq_uniq").on(t.orgId, t.seq),
    auditEventsOrgIdIdx: index("audit_events_org_id_idx").on(t.orgId),
}));
