// AUTO-GENERATED by scripts/gen-schema.mjs — DO NOT EDIT.
// Source of truth: scripts/db-spec.mjs. Regenerate: npm run db:gen
import { sqliteTable, text, integer, real, uniqueIndex, index } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { createId } from "../lib/utils";

export const organizations = sqliteTable("organizations", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  name: text("name").notNull(),
  slug: text("slug").notNull(),
  planId: text("plan_id"),
  signingKeyId: text("signing_key_id"),
  createdAt: integer("created_at").notNull(),
  archivedAt: integer("archived_at"),
}, (t) => ({
    organizationsSlugUniq: uniqueIndex("organizations_slug_uniq").on(t.slug),
}));

export const users = sqliteTable("users", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  name: text("name").notNull(),
  email: text("email").notNull(),
  passwordHash: text("password_hash"),
  emailVerified: integer("email_verified"),
  image: text("image"),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    usersEmailUniq: uniqueIndex("users_email_uniq").on(t.email),
}));

export const memberships = sqliteTable("memberships", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
  role: text("role").notNull().default("viewer"),
  invitedBy: text("invited_by"),
  invitedAt: integer("invited_at"),
  acceptedAt: integer("accepted_at"),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    membershipsOrgIdUserIdUniq: uniqueIndex("memberships_org_id_user_id_uniq").on(t.orgId, t.userId),
    membershipsUserIdIdx: index("memberships_user_id_idx").on(t.userId),
}));

export const sessions = sqliteTable("sessions", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
  orgId: text("org_id"),
  tokenHash: text("token_hash").notNull(),
  ip: text("ip"),
  userAgent: text("user_agent"),
  lastSeenAt: integer("last_seen_at"),
  revokedAt: integer("revoked_at"),
  expiresAt: integer("expires_at").notNull(),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    sessionsTokenHashUniq: uniqueIndex("sessions_token_hash_uniq").on(t.tokenHash),
    sessionsUserIdIdx: index("sessions_user_id_idx").on(t.userId),
}));

export const projects = sqliteTable("projects", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  name: text("name").notNull(),
  description: text("description"),
  agentEndpoint: text("agent_endpoint"),
  agentMethod: text("agent_method").notNull().default("POST"),
  agentType: text("agent_type"),
  agentHeaders: text("agent_headers", { mode: "json" }),
  defaultModel: text("default_model").notNull().default("gpt-4o-mini"),
  judgeBaseUrl: text("judge_base_url"),
  judgeModel: text("judge_model"),
  createdBy: text("created_by"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (t) => ({
    projectsOrgIdIdx: index("projects_org_id_idx").on(t.orgId),
}));

export const secrets = sqliteTable("secrets", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  refType: text("ref_type").notNull(),
  refId: text("ref_id").notNull(),
  name: text("name").notNull(),
  ciphertext: text("ciphertext").notNull(),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (t) => ({
    secretsOrgIdRefTypeRefIdNameUniq: uniqueIndex("secrets_org_id_ref_type_ref_id_name_uniq").on(t.orgId, t.refType, t.refId, t.name),
}));

export const testCases = sqliteTable("test_cases", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  title: text("title").notNull(),
  input: text("input").notNull(),
  expectedOutput: text("expected_output"),
  context: text("context"),
  category: text("category"),
  order: integer("order").notNull().default(0),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (t) => ({
    testCasesOrgIdIdx: index("test_cases_org_id_idx").on(t.orgId),
    testCasesProjectIdIdx: index("test_cases_project_id_idx").on(t.projectId),
}));

export const runs = sqliteTable("runs", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  name: text("name"),
  status: text("status").notNull().default("queued"),
  totalCases: integer("total_cases").notNull().default(0),
  passCount: integer("pass_count").notNull().default(0),
  failCount: integer("fail_count").notNull().default(0),
  partialCount: integer("partial_count").notNull().default(0),
  unratedCount: integer("unrated_count").notNull().default(0),
  passRate: integer("pass_rate"),
  triggerType: text("trigger_type").notNull().default("manual"),
  triggeredBy: text("triggered_by"),
  modelUsed: text("model_used"),
  createdAt: integer("created_at").notNull(),
  completedAt: integer("completed_at"),
}, (t) => ({
    runsOrgIdIdx: index("runs_org_id_idx").on(t.orgId),
    runsProjectIdIdx: index("runs_project_id_idx").on(t.projectId),
}));

export const runResults = sqliteTable("run_results", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runId: text("run_id").references(() => runs.id, { onDelete: "cascade" }).notNull(),
  testCaseId: text("test_case_id").references(() => testCases.id, { onDelete: "cascade" }).notNull(),
  agentResponse: text("agent_response"),
  responseTimeMs: integer("response_time_ms"),
  status: text("status").notNull().default("pending"),
  errorMessage: text("error_message"),
  needsHuman: integer("needs_human", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    runResultsOrgIdIdx: index("run_results_org_id_idx").on(t.orgId),
    runResultsRunIdIdx: index("run_results_run_id_idx").on(t.runId),
}));

export const jobs = sqliteTable("jobs", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  type: text("type").notNull(),
  payload: text("payload", { mode: "json" }),
  status: text("status").notNull().default("queued"),
  attempts: integer("attempts").notNull().default(0),
  maxAttempts: integer("max_attempts").notNull().default(3),
  runAfter: integer("run_after").notNull(),
  lockedAt: integer("locked_at"),
  lockedBy: text("locked_by"),
  lastError: text("last_error"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (t) => ({
    jobsStatusIdx: index("jobs_status_idx").on(t.status),
    jobsOrgIdIdx: index("jobs_org_id_idx").on(t.orgId),
}));

export const apiKeys = sqliteTable("api_keys", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id"),
  name: text("name").notNull(),
  keyHash: text("key_hash").notNull(),
  keyPrefix: text("key_prefix").notNull(),
  scopes: text("scopes", { mode: "json" }),
  createdBy: text("created_by"),
  lastUsedAt: integer("last_used_at"),
  expiresAt: integer("expires_at"),
  revokedAt: integer("revoked_at"),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    apiKeysKeyHashUniq: uniqueIndex("api_keys_key_hash_uniq").on(t.keyHash),
    apiKeysOrgIdIdx: index("api_keys_org_id_idx").on(t.orgId),
}));

export const rubrics = sqliteTable("rubrics", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  name: text("name").notNull(),
  version: integer("version").notNull().default(1),
  kind: text("kind").notNull().default("ordinal"),
  labels: text("labels", { mode: "json" }).notNull(),
  scaleMin: integer("scale_min"),
  scaleMax: integer("scale_max"),
  alwaysHuman: integer("always_human", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    rubricsProjectIdNameVersionUniq: uniqueIndex("rubrics_project_id_name_version_uniq").on(t.projectId, t.name, t.version),
    rubricsOrgIdIdx: index("rubrics_org_id_idx").on(t.orgId),
    rubricsProjectIdIdx: index("rubrics_project_id_idx").on(t.projectId),
}));

export const aiScores = sqliteTable("ai_scores", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runResultId: text("run_result_id").references(() => runResults.id, { onDelete: "cascade" }).notNull(),
  rubricVersionId: text("rubric_version_id"),
  judgeConfigVersionId: text("judge_config_version_id"),
  provider: text("provider"),
  model: text("model").notNull(),
  modelResolved: text("model_resolved"),
  promptHash: text("prompt_hash"),
  label: text("label").notNull(),
  scoreNum: real("score_num"),
  confidence: real("confidence"),
  selfConsistency: real("self_consistency"),
  disagreement: real("disagreement"),
  rationale: text("rationale"),
  raw: text("raw", { mode: "json" }),
  idempotencyKey: text("idempotency_key").notNull(),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    aiScoresIdempotencyKeyUniq: uniqueIndex("ai_scores_idempotency_key_uniq").on(t.idempotencyKey),
    aiScoresOrgIdIdx: index("ai_scores_org_id_idx").on(t.orgId),
    aiScoresRunResultIdIdx: index("ai_scores_run_result_id_idx").on(t.runResultId),
}));

export const humanRatings = sqliteTable("human_ratings", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runResultId: text("run_result_id").references(() => runResults.id, { onDelete: "cascade" }).notNull(),
  rubricVersionId: text("rubric_version_id"),
  reviewerId: text("reviewer_id"),
  label: text("label").notNull(),
  scoreNum: real("score_num"),
  rationale: text("rationale"),
  confidence: real("confidence"),
  supersedesId: text("supersedes_id"),
  credentialSnapshot: text("credential_snapshot", { mode: "json" }),
  signature: text("signature"),
  signingKeyId: text("signing_key_id"),
  attemptId: text("attempt_id").notNull(),
  signedAt: integer("signed_at"),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    humanRatingsRunResultIdReviewerIdAttemptIdUniq: uniqueIndex("human_ratings_run_result_id_reviewer_id_attempt_id_uniq").on(t.runResultId, t.reviewerId, t.attemptId),
    humanRatingsOrgIdIdx: index("human_ratings_org_id_idx").on(t.orgId),
    humanRatingsRunResultIdIdx: index("human_ratings_run_result_id_idx").on(t.runResultId),
    humanRatingsRunResultIdReviewerIdCurrentUniq: uniqueIndex("human_ratings_run_result_id_reviewer_id_current_uniq").on(t.runResultId, t.reviewerId).where(sql`${t.supersedesId} is null`),
}));

export const adjudications = sqliteTable("adjudications", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runResultId: text("run_result_id").references(() => runResults.id, { onDelete: "cascade" }).notNull(),
  rubricVersionId: text("rubric_version_id"),
  finalLabel: text("final_label").notNull(),
  method: text("method").notNull(),
  weightingScheme: text("weighting_scheme"),
  agreementSummary: text("agreement_summary", { mode: "json" }),
  decidedBy: text("decided_by"),
  decidedAt: integer("decided_at").notNull(),
  locked: integer("locked", { mode: "boolean" }).notNull().default(false),
}, (t) => ({
    adjudicationsRunResultIdUniq: uniqueIndex("adjudications_run_result_id_uniq").on(t.runResultId),
    adjudicationsOrgIdIdx: index("adjudications_org_id_idx").on(t.orgId),
}));

export const agreementMetrics = sqliteTable("agreement_metrics", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  scopeType: text("scope_type").notNull(),
  scopeId: text("scope_id").notNull(),
  rubricVersionId: text("rubric_version_id"),
  aiHumanAgreementPct: real("ai_human_agreement_pct"),
  aiHumanConfusion: text("ai_human_confusion", { mode: "json" }),
  kappa: real("kappa"),
  kappaMethod: text("kappa_method"),
  weightingScheme: text("weighting_scheme"),
  nItems: integer("n_items"),
  nRaters: integer("n_raters"),
  ciLo: real("ci_lo"),
  ciHi: real("ci_hi"),
  windowStart: integer("window_start"),
  windowEnd: integer("window_end"),
  computedAt: integer("computed_at").notNull(),
}, (t) => ({
    agreementMetricsOrgIdIdx: index("agreement_metrics_org_id_idx").on(t.orgId),
    agreementMetricsScopeTypeScopeIdIdx: index("agreement_metrics_scope_type_scope_id_idx").on(t.scopeType, t.scopeId),
}));

export const judgeCalibration = sqliteTable("judge_calibration", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  judgeModel: text("judge_model").notNull(),
  judgePromptHash: text("judge_prompt_hash"),
  weightingScheme: text("weighting_scheme"),
  windowStart: integer("window_start"),
  windowEnd: integer("window_end"),
  sampleN: integer("sample_n"),
  auditSampleN: integer("audit_sample_n"),
  agreementPct: real("agreement_pct"),
  weightedKappa: real("weighted_kappa"),
  confusion: text("confusion", { mode: "json" }),
  bias: text("bias", { mode: "json" }),
  meanAbsScoreError: real("mean_abs_score_error"),
  tau: real("tau"),
  published: integer("published", { mode: "boolean" }).notNull().default(false),
  computedAt: integer("computed_at").notNull(),
}, (t) => ({
    judgeCalibrationOrgIdIdx: index("judge_calibration_org_id_idx").on(t.orgId),
    judgeCalibrationProjectIdIdx: index("judge_calibration_project_id_idx").on(t.projectId),
}));

export const signoffPolicies = sqliteTable("signoff_policies", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id").references(() => projects.id, { onDelete: "cascade" }).notNull(),
  minReviewers: integer("min_reviewers").notNull().default(1),
  requiredRole: text("required_role"),
  requireVerifiedCredential: integer("require_verified_credential", { mode: "boolean" }).notNull().default(false),
  minKappa: real("min_kappa"),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  createdBy: text("created_by"),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    signoffPoliciesOrgIdIdx: index("signoff_policies_org_id_idx").on(t.orgId),
    signoffPoliciesProjectIdIdx: index("signoff_policies_project_id_idx").on(t.projectId),
}));

export const runSignoffs = sqliteTable("run_signoffs", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runId: text("run_id").references(() => runs.id, { onDelete: "cascade" }).notNull(),
  reviewerId: text("reviewer_id").notNull(),
  decision: text("decision").notNull(),
  note: text("note"),
  credentialSnapshot: text("credential_snapshot", { mode: "json" }),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    runSignoffsRunIdReviewerIdUniq: uniqueIndex("run_signoffs_run_id_reviewer_id_uniq").on(t.runId, t.reviewerId),
    runSignoffsOrgIdIdx: index("run_signoffs_org_id_idx").on(t.orgId),
    runSignoffsRunIdIdx: index("run_signoffs_run_id_idx").on(t.runId),
}));

export const signingKeys = sqliteTable("signing_keys", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id"),
  publicKeyPem: text("public_key_pem").notNull(),
  privateKeySecretId: text("private_key_secret_id"),
  algo: text("algo").notNull().default("ed25519"),
  createdAt: integer("created_at").notNull(),
  retiredAt: integer("retired_at"),
}, (t) => ({
    signingKeysOrgIdIdx: index("signing_keys_org_id_idx").on(t.orgId),
}));

export const evalCertificates = sqliteTable("eval_certificates", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  runId: text("run_id").references(() => runs.id, { onDelete: "cascade" }).notNull(),
  contentHash: text("content_hash").notNull(),
  signature: text("signature").notNull(),
  signingKeyId: text("signing_key_id").notNull(),
  algo: text("algo").notNull().default("ed25519"),
  publicKeyPem: text("public_key_pem").notNull(),
  canonicalJson: text("canonical_json"),
  payload: text("payload", { mode: "json" }),
  weightingScheme: text("weighting_scheme"),
  isPublic: integer("is_public", { mode: "boolean" }).notNull().default(false),
  signedAt: integer("signed_at").notNull(),
  expiresAt: integer("expires_at"),
}, (t) => ({
    evalCertificatesRunIdUniq: uniqueIndex("eval_certificates_run_id_uniq").on(t.runId),
    evalCertificatesOrgIdIdx: index("eval_certificates_org_id_idx").on(t.orgId),
}));

export const webhooks = sqliteTable("webhooks", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  projectId: text("project_id"),
  url: text("url").notNull(),
  secretCiphertext: text("secret_ciphertext").notNull(),
  events: text("events", { mode: "json" }).notNull(),
  isActive: integer("is_active", { mode: "boolean" }).notNull().default(true),
  createdBy: text("created_by"),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    webhooksOrgIdIdx: index("webhooks_org_id_idx").on(t.orgId),
    webhooksProjectIdIdx: index("webhooks_project_id_idx").on(t.projectId),
}));

export const webhookDeliveries = sqliteTable("webhook_deliveries", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  webhookId: text("webhook_id").references(() => webhooks.id, { onDelete: "cascade" }).notNull(),
  event: text("event").notNull(),
  payload: text("payload", { mode: "json" }),
  status: text("status").notNull().default("pending"),
  attempts: integer("attempts").notNull().default(0),
  responseStatus: integer("response_status"),
  lastError: text("last_error"),
  createdAt: integer("created_at").notNull(),
  updatedAt: integer("updated_at").notNull(),
}, (t) => ({
    webhookDeliveriesOrgIdIdx: index("webhook_deliveries_org_id_idx").on(t.orgId),
    webhookDeliveriesWebhookIdIdx: index("webhook_deliveries_webhook_id_idx").on(t.webhookId),
}));

export const rateLimits = sqliteTable("rate_limits", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  bucket: text("bucket").notNull(),
  windowStart: integer("window_start").notNull(),
  count: integer("count").notNull().default(0),
}, (t) => ({
    rateLimitsBucketWindowStartUniq: uniqueIndex("rate_limits_bucket_window_start_uniq").on(t.bucket, t.windowStart),
    rateLimitsWindowStartIdx: index("rate_limits_window_start_idx").on(t.windowStart),
}));

export const passwordResetTokens = sqliteTable("password_reset_tokens", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  userId: text("user_id").references(() => users.id, { onDelete: "cascade" }).notNull(),
  tokenHash: text("token_hash").notNull(),
  expiresAt: integer("expires_at").notNull(),
  usedAt: integer("used_at"),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    passwordResetTokensTokenHashUniq: uniqueIndex("password_reset_tokens_token_hash_uniq").on(t.tokenHash),
    passwordResetTokensUserIdIdx: index("password_reset_tokens_user_id_idx").on(t.userId),
}));

export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey().$defaultFn(() => createId()),
  orgId: text("org_id").references(() => organizations.id, { onDelete: "cascade" }).notNull(),
  seq: integer("seq").notNull(),
  actorId: text("actor_id"),
  action: text("action").notNull(),
  resourceType: text("resource_type"),
  resourceId: text("resource_id"),
  details: text("details", { mode: "json" }),
  prevHash: text("prev_hash").notNull(),
  hash: text("hash").notNull(),
  createdAt: integer("created_at").notNull(),
}, (t) => ({
    auditEventsOrgIdSeqUniq: uniqueIndex("audit_events_org_id_seq_uniq").on(t.orgId, t.seq),
    auditEventsOrgIdIdx: index("audit_events_org_id_idx").on(t.orgId),
}));
