// ============================================================================
// Schema codegen — emits per-dialect Drizzle modules from scripts/db-spec.mjs.
//
//   node scripts/gen-schema.mjs          # writes src/db/schema.{pg,sqlite}.ts
//   import { generate } from gen-schema   # returns { pg, sqlite } strings (drift test)
//
// The generated files are checked in. CI re-runs this and fails on any diff,
// guaranteeing the two dialects stay structurally identical.
// ============================================================================

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { tables, exportName } from "./db-spec.mjs";

const camel = (s) => s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
const lit = (v) =>
  typeof v === "string" ? JSON.stringify(v) : typeof v === "boolean" ? String(v) : String(v);

// --- per-dialect column expression builders -------------------------------

function pgColumn(name, col) {
  switch (col.kind) {
    case "id":
      return `text(${JSON.stringify(name)}).primaryKey().$defaultFn(() => createId())`;
    case "text":
    case "fk":
      return `text(${JSON.stringify(name)})`;
    case "ts":
      return `bigint(${JSON.stringify(name)}, { mode: "number" })`;
    case "int":
      return `integer(${JSON.stringify(name)})`;
    case "json":
      return `jsonb(${JSON.stringify(name)})`;
    case "bool":
      return `boolean(${JSON.stringify(name)})`;
    case "num":
      // doublePrecision (float8) returns a JS number on PG — true parity with
      // SQLite `real`. `numeric` would return a STRING, breaking the
      // identical-results-across-drivers rule for statistical columns.
      return `doublePrecision(${JSON.stringify(name)})`;
    default:
      throw new Error(`pg: unknown column kind ${col.kind}`);
  }
}

function sqliteColumn(name, col) {
  switch (col.kind) {
    case "id":
      return `text(${JSON.stringify(name)}).primaryKey().$defaultFn(() => createId())`;
    case "text":
    case "fk":
      return `text(${JSON.stringify(name)})`;
    case "ts":
    case "int":
      return `integer(${JSON.stringify(name)})`;
    case "json":
      return `text(${JSON.stringify(name)}, { mode: "json" })`;
    case "bool":
      return `integer(${JSON.stringify(name)}, { mode: "boolean" })`;
    case "num":
      return `real(${JSON.stringify(name)})`;
    default:
      throw new Error(`sqlite: unknown column kind ${col.kind}`);
  }
}

function decorate(expr, name, col) {
  let out = expr;
  if (col.kind === "fk") {
    const [refTable, refCol] = col.ref.split(".");
    const onDelete = col.onDelete ? `, { onDelete: ${JSON.stringify(col.onDelete)} }` : "";
    out += `.references(() => ${exportName(refTable)}.${camel(refCol)}${onDelete})`;
  }
  if (col.nullable === false && col.kind !== "id") out += ".notNull()";
  if (col.default !== undefined) out += `.default(${lit(col.default)})`;
  return out;
}

function tableBlock(table, columnFn) {
  const v = exportName(table.name);
  const tableFn = columnFn === pgColumn ? "pgTable" : "sqliteTable";

  const cols = Object.entries(table.columns)
    .map(([name, col]) => `  ${camel(name)}: ${decorate(columnFn(name, col), name, col)},`)
    .join("\n");

  const extras = [];
  for (const u of table.uniques || []) {
    const idxName = `${table.name}_${u.join("_")}_uniq`;
    const on = u.map((c) => `t.${camel(c)}`).join(", ");
    extras.push(`    ${camel(idxName)}: uniqueIndex(${JSON.stringify(idxName)}).on(${on}),`);
  }
  for (const i of table.indexes || []) {
    const idxName = `${table.name}_${i.join("_")}_idx`;
    const on = i.map((c) => `t.${camel(c)}`).join(", ");
    extras.push(`    ${camel(idxName)}: index(${JSON.stringify(idxName)}).on(${on}),`);
  }
  // Partial unique indexes — { cols, whereNull }: UNIQUE(cols) WHERE <whereNull> IS NULL.
  // Both engines support partial indexes; this enforces e.g. "one CURRENT
  // (non-superseded) human rating per reviewer" structurally on both drivers.
  for (const pu of table.partialUniques || []) {
    const idxName = `${table.name}_${pu.cols.join("_")}_current_uniq`;
    const on = pu.cols.map((c) => `t.${camel(c)}`).join(", ");
    extras.push(
      "    " +
        camel(idxName) +
        ": uniqueIndex(" +
        JSON.stringify(idxName) +
        ").on(" +
        on +
        ").where(sql`" +
        "${t." +
        camel(pu.whereNull) +
        "} is null`),",
    );
  }

  const tail = extras.length
    ? `, (t) => ({\n${extras.join("\n")}\n})`
    : "";

  return `export const ${v} = ${tableFn}(${JSON.stringify(table.name)}, {\n${cols}\n}${tail});`;
}

const BANNER = `// AUTO-GENERATED by scripts/gen-schema.mjs — DO NOT EDIT.
// Source of truth: scripts/db-spec.mjs. Regenerate: npm run db:gen
`;

export function generate() {
  const pg = `${BANNER}import { pgTable, text, bigint, integer, jsonb, boolean, doublePrecision, uniqueIndex, index } from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { createId } from "../lib/utils";

${tables.map((t) => tableBlock(t, pgColumn)).join("\n\n")}
`;

  const sqlite = `${BANNER}import { sqliteTable, text, integer, real, uniqueIndex, index } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";
import { createId } from "../lib/utils";

${tables.map((t) => tableBlock(t, sqliteColumn)).join("\n\n")}
`;

  return { pg, sqlite };
}

// CLI: write the files.
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const { pg, sqlite } = generate();
  const dbDir = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "db");
  writeFileSync(join(dbDir, "schema.pg.ts"), pg);
  writeFileSync(join(dbDir, "schema.sqlite.ts"), sqlite);
  console.log("Generated src/db/schema.pg.ts and src/db/schema.sqlite.ts");
}
